# Generated by Django 4.1.5 on 2023-01-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
