# Generated by Django 4.1.5 on 2023-01-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_product_comparison', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
