# Generated by Django 4.1.5 on 2023-01-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_product_comparison', '0003_rename_phone_shopdetail_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='specifications',
            new_name='specification',
        ),
    ]
